DROP TABLE PRODUCTS IF EXISTS;

CREATE TABLE PRODUCTS (
	ID VARCHAR(25) PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(250),
	UNIT_PRICE DECIMAL,
	MANUFACTURER VARCHAR(50),
	CATEGORY VARCHAR(50),
	CONDITION VARCHAR(50),
	UNITS_IN_STOCK BIGINT,
	UNITS_IN_ORDER BIGINT,
	DISCONTINUED BOOLEAN
);

DROP TABLE USERS IF EXISTS;

CREATE TABLE USERS (
	ID VARCHAR(25) PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	IS_ADMIN BOOLEAN
);